
// Action Keys

export const SET_NUMBER_OF_BEDS = "SET_NUMBER_OF_BEDS";
export const SET_NUMBER_OF_GUESTS = "SET_NUMBER_OF_GUESTS";
export const SET_NUMBER_OF_PETS = "SET_NUMBER_OF_PETS";
export const SET_NUMBER_OF_CHILDREN = "SET_NUMBER_OF_CHILDREN";
export const SET_NUMBER_OF_ROOMS = "SET_NUMBER_OF_ROOMS";
export const SET_NUMBER_OF_BATHROOMS = "SET_NUMBER_OF_BATHROOMS";
export const SET_MIN_MAx_NIGHTS = "SET_MIN_MAx_NIGHTS";
export const SET_APARTMENT_TITLE = "SET_APARTMENT_TITLE";
export const SET_APARTMENT_DESCRIPTION = "SET_APARTMENT_DESCRIPTION";
export const SET_APARTMENT_ADDRESS = "SET_APARTMENT_ADDRESS";
export const SET_APARTMENT_CITY_LOCATION = "SET_APARTMENT_CITY_LOCATION";
export const SET_APARTMENT_STATE_LOCATITION = "SET_APARTMENT_STATE_LOCATITION";
export const SET_APARTMENT_COUNTRY_LOCATITION = "SET_APARTMENT_COUNTRY_LOCATITION";
export const SET_APARTMENT_HAS_WIFI = "SET_APARTMENT_HAS_WIFI";
export const SET_APARTMENT_HAS_TV_CABLE = "SET_APARTMENT_HAS_TV_CABLE";
export const SET_APARTMENT_HAS_SECURITY = "SET_APARTMENT_HAS_SECURITY";
export const SET_APARTMENT_HAS_GYM = "SET_APARTMENT_HAS_GYM";
export const SET_APARTMENT_HAS_LAUNDARY = "SET_APARTMENT_HAS_LAUNDARY";
export const SET_APARTMENT_TYPE = "SET_APARTMENT_TYPE";
export const SET_SMOKING_ALLOWED = "SET_SMOKING_ALLOWED";
export const SET_PETS_ALLOWED = "SET_PETS_ALLOWED";
export const SET_CHILDREN_ALLOWED = "SET_CHILDREN_ALLOWED";
export const SET_PARTY_ALLOWED = "SET_PARTY_ALLOWED";
export const SET_CHECIN_TIME = "SET_CHECIN_TIME";
export const SET_CHECKOUT_TIME = "SET_CHECKOUT_TIME";
export const SET_APARTMENT_IMAGE_1 = "SET_APARTMENT_IMAGE_1";
export const SET_APARTMENT_IMAGE_2 = "SET_APARTMENT_IMAGE_2";
export const SET_APARTMENT_IMAGE_3 = "SET_APARTMENT_IMAGE_3";
export const SET_PRICE_PER_NIGHT= "SET_PRICE_PER_NIGHT";
export const SET_ALL_APARTMENT_DETAILS = "SET_ALL_APARTMENT_DETAILS"